import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [input, setInput] = useState("");
  const [error, setError] = useState(false);
  const [suggestion, setSuggestion] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (input.length < 30) setError(false);
  }, [input]);

  const submit = async () => {
    // Check if character limit is exceeded
    if (input.length > 30) return setError(true);
    // Set Loading state
    setLoading(true);

    try {
      const res = await fetch("api/marketing-copy", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ input }),
      });
      const suggestion = await res.json();
      
      setSuggestion(suggestion.input);
    } catch (error) {
      console.log(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Marketing Copy Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-7xl mx-auto py-12">
        <h2 className="text-2xl font-bold text-center ">
          Marketing Copy Generator
        </h2>
        {/*  Input field for marketing copy */}
        <div className="flex justify-center gap-4 flex-col mx-auto">
          <div className="relative w-full">
            {error && (
              <div className="absolute top-0 left-0 text-red-500 text-xs">
                <p className="text-xs pt-1 text-red-500">
                  Character limit exceeded, please enter less text
                </p>
              </div>
            )}
            <textarea
              rows={3}
              onChange={(e) => setInput(e.target.value)}
              value={input}
              className="w-full border-2 border-gray-300 bg-white p-4 rounded-lg text-sm focus:outline-none resize-none"
              placeholder="Enter your marketing copy here"
            />
            {/* Character limit in bottom right of textarea */}
            <div
              className={` ${
                input.length > 30 ? "text-red-500" : "text-gray-400"
              } absolute bottom-2 right-2  text-xs`}
            >
              <span>{input.length}</span>/30
            </div>
          </div>
          <button
            type="button"
            onClick={submit}
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-4 rounded"
          >
            {loading ? 'Loading...' : "Generate"}
          </button>
          {/* Output field for marketing copy */}
          {suggestion && (
            <div>
              <h4 className="text-lg font-semibold">Your marketing copy:</h4>
              <div className="relative w-full rounded-md bg-gray-100">
                <p className="text-sm text-gray-700">{suggestion}</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Home;
